@echo off
echo Starting Pipeline...

echo 1. Extracting frames from medium dataset...
venv\Scripts\python.exe src\processVideos.py

echo 2. Extracting faces from frames...
venv\Scripts\python.exe src\processFaces.py

echo 3. Splitting dataset for 2D models...
venv\Scripts\python.exe src\splitDataset.py

echo 4. Training 2D Model (Xception)...
venv\Scripts\python.exe src\trainXception.py > train2d_log.txt 2>&1

echo 5. Training 3D Model...
venv\Scripts\python.exe src\train3D.py > train3d_log.txt 2>&1

echo 6. Final Evaluation Fusion Model...
venv\Scripts\python.exe src\evaluateFINAL.py > evaluate_log.txt 2>&1

echo Pipeline completed! You can check the log files.
